apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace:  my-web-apps  # ← ДОБАВИТЬ namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace:  my-web-apps  # ← ДОБАВИТЬ namespace
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace:  my-web-apps  # ← ДОБАВИТЬ namespace
  annotations:
    external-dns.alpha.kubernetes.io/hostname: web.stellarclaw.ru
    cert-manager.io/cluster-issuer: "letsencrypt-dev"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - web.stellarclaw.ru
    secretName: nginx-tls
  rules:
  - host: web.stellarclaw.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
